### ISSUE TITLE
Question about the matrix I

### ISSUE THREAD

**Issue by hhuxuchang** [Zhaozixiang1228/GDSR-DCTNet#1]
Since the equation (4) in the paper contains the identity matrix I
The matrix I is implemented with 1,  does it right?

**Comment by hhuxuchang** [comment]
![image](https://user-images.githubusercontent.com/83766440/181185201-1ba8d80f-cfe4-44e1-b131-d760f236d850.png)

**Comment by Zhaozixiang1228** [comment]
Thanks for your reminders and suggestions. $I$ should be an all-ones matrix, which is a typo in the paper. The implementation of the code is correct. I will update a corrected version of the paper on arXiv.

**Comment by hhuxuchang** [comment]
Thanks,for another question 
Could you give some detail about the calculation of gradient of $L(H)$

Since the derivative of $||H-L||^2_2$ is $2(H-L)$
should the derivative of $||L(H)-L(R)W(R)||^2_2$ is $2(L(H)-L(R)W(R))$
why the derivative is $2L(L(H)-L(R)W(R))$?
could you give me some literature about this equation about gradient?
thanks again!

**Comment by Zhaozixiang1228** [comment]
More details can be found in the supplementary material of the paper, which contains detailed derivations and references.
