### ISSUE TITLE
Question about LR_UP_Patches.

### ISSUE THREAD

**Issue by Guanys-dar** [Zhaozixiang1228/GDSR-DCTNet#6]
Why we need to save["LR_UP_Patches"(1,256,256)? ](https://github.com/Zhaozixiang1228/GDSR-DCTNet/blob/5243875223398fd7996bca2e54dc2792bb96862a/utils_gdsr.py#L140). 

According to my understanding, we need LR depths with size of (1,256//scale,256//scale), HR depths with size of(1,256,256). Why we need LR_UP_Patches?

**Comment by MuggleTan** [comment]
Hello, did you find it out?
I have the same question.

I wonder whether the resolution of the final super-resolutioned depth map is 256 * 256?

Looking for your reply.

**Comment by Guanys-dar** [comment]
It is actually a naive question, the author upsample the LR images to the size of HR, to avoid upsampling operation in the designed network. :)
