### ISSUE TITLE
fft_rfft() got an unexpected keyword argument 'onesided'

### ISSUE THREAD

**Issue by epicman22** [Zhaozixiang1228/GDSR-DCTNet#8]
TypeError: fft_rfft() got an unexpected keyword argument 'onesided'
torch version 1.13

**Comment by epicman22** [comment]
Solution
Replace torch.rfft with  torch.view_as_real(torch.fft.fft()) and remove "onesided"
eg:
Original
    Vc = torch.rfft(v, 1, onesided=False)
Solution:
    Vc = torch.view_as_real(torch.fft.fft(v, dim=1))

**Comment by Zhaozixiang1228** [comment]
My torch version is: torch==1.7.1. You can run the code in this environment.

**Comment by Adrian13155** [comment]
事实上，除了`Vc = torch.rfft(v, 1, onesided=False)`要改成`Vc = torch.view_as_real(torch.fft.fft(v, dim=1))`，还需要将`v = torch.irfft(V, 1, onesided=False)`改成`V_complex = torch.view_as_complex(V)`和`v = torch.fft.irfft(V_complex, dim=1,n=N)`
